# Плохой Dockerfile
FROM python:3.8-slim

# Установка зависимостей
RUN apt-get update
RUN apt-get install -y python3-pip

# Установка Jupyter
RUN pip install jupyter

# Копирование рабочего каталога
COPY . /app

# Установка зависимостей из requirements.txt
RUN pip install -r /app/requirements.txt

# Установка прав на рабочий каталог
RUN chmod -R 777 /app

# Указание рабочей директории
WORKDIR /app

# Монтирование volume для хранения данных
VOLUME /app/data

# Запуск Jupyter
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]