---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-2-config
data:
  index.html: |
    <html>
    <head><title>Service 2</title></head>
    <body>
    <h1>Welcome to Service 2</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-deployment
  labels:
    app: service-2
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
      tier: frontend
  template:
    metadata:
      labels:
        app: service-2
        tier: frontend
    spec:
      containers:
      - name: service-2
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: service-2-config
