---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-1-config
data:
  config.yaml: |
    key: value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-deployment
  labels:
    app: service-1
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
      tier: backend
  template:
    metadata:
      labels:
        app: service-1
        tier: backend
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: service-1-config
      initContainers:
      - name: init-service-1
        image: busybox
        command: ['sh', '-c', 'echo "Init container completed"']
      containers:
      - name: service-1
        image: thecodedemogorgon/custom-service:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/config
          name: config-volume
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: service-1-service
spec:
  selector:
    app: service-1
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
